Handle gracefully code locations missing
Roave/BackwardCompatibilityCheck pull request #697
Opened 2022-11-22 15:23 UTC by DanielBadura

Coming from https://github.com/Roave/BetterReflection/issues/1309.

First draft of handling the code location missing error. First, only in those places needed to handle the issue provided in the linked issue of BetterReflection. But i think the other one should be updated too, right?

2022-11-22 16:06 UTC, Ocramius requested changes

2022-11-22 16:06 UTC, Ocramius commented on test/unit/Formatter/SymbolStartTest.php
> +    public function testCannotGetStartLineWhenAstHasBeenParsedWithoutColumnLocations(): void
Without  **Line** locations

2022-11-23 08:40 UTC, DanielBadura commented on test/unit/Formatter/SymbolStartTest.php
> +    public function testCannotGetStartLineWhenAstHasBeenParsedWithoutColumnLocations(): void
Adjusted :)

2022-11-23 09:05 UTC, Ocramius approved these changes
Thanks @DanielBadura!

2022-11-23 09:06 UTC, Ocramius commented
Interesting: CI failed on your fork because you only had very old tags in it :D

2022-11-23 09:08 UTC, merged

2022-11-23 09:09 UTC, DanielBadura commented
Yeah dont know why the fork is so outdated. I updated it before i started the work on this patch 😅